# MongoDB
jnosql.document.database=CoT_Project
jnosql.mongodb.host=127.0.0.1:27017
jnosql.document.provider=org.eclipse.jnosql.databases.mongodb.communication.MongoDBDocumentConfiguration

# MQTT - Broker local
mqtt.uri=ssl://f7650e29f2d1418ab38a502a12ae2a8e.s1.eu.hivemq.cloud:8883
mqtt.username=marwen
mqtt.password=M1arwen#
mqtt.topic.sensors=iot/data
mqtt.topic.actuators=iot/control

# IAM Configuration
iam.url=http://localhost:8080/iam/rest-iam

# MP-JWT Verification
mp.jwt.verify.publickey.location=http://localhost:8080/iam/rest-iam/jwk/keys
mp.jwt.verify.issuer=urn:me.greenhouse.iam
mp.jwt.token.cookie=access_token
